config/routes.rb
require 'api_version'

RoutesTest::Application.routes.draw do

  constraints subdomain: 'api' do
    scope module: 'api', defaults: { format: 'json' } do
      constraints ApiVersion[1] do
        scope module: 'v1' do
          resources :users
        end
      end
      constraints ApiVersion[2] do
        scope module: 'v2' do
          resources :users
        end
      end
      root to: 'home#welcome'
    end
  end

  scope 'admin' do
    match "users" => 'users#index', :as => :users
  end

  match 'about' => 'home#about', :as => :about
  match 'welcome' => 'home#welcome', :as => :welcome
  get 'profile' => 'users#show', :id => 2

  constraints(subdomain: 'stats') do
    resources :users
  end

  root :to => 'home#welcome'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :bdate

  validates_uniqueness_of :email, :on => :create, :message => "already registered"

  scope :until85, where("bdate <= ?", Time.new(1985, 12, 31).to_date)
  scope :after85, where("bdate > ?", Time.new(1985, 12, 31).to_date)
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def show
    @user = User.find_by_id(params[:id])
    render json: @user
  end

  def index
    @users = User.all
    render json: @users
  end
end

app/controllers/api/v2/users_controller.rb
class Api::V2::UsersController < ApplicationController
  def show
    @user = User.find_by_id(1)
    render json: @user
  end

  def index
    @users = User.all[0..2]
    render json: @users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def welcome
    @names = User.all.map(&:name)
    respond_to do |format|
      format.html
      format.json { render json: @names }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

<%= debug params %>

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

<%= request.subdomain %>
<%= debug params %>
<%= debug request %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoutesTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Birth Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.bdate %></td>
    <td><%= link_to 'XML', user_url(user, subdomain: 'api', format: 'xml') %></td>
    <td><%= link_to 'JSON', user_url(user, subdomain: 'api', :format => 'json') %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= path_methods = methods.reject {|method| method =~ /hash/ }.select {|method| method =~ /api/ } %>

<br />

<%= link_to 'Profile', profile_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Birth Date:</b>
  <%= @user.bdate %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>